from .globals import (
    SAMPLE_RATE, DURATION, N_FFT, HOP_LENGTH, N_MELS,
    LATENT_CHANNELS,
    BATCH_SIZE, AE_EPOCHS, DIFF_EPOCHS, LR, KL_WEIGHT, KL_ANNEAL_EPOCHS,
    T,
    DATA_GLOB, GEN_SAMPLE_PATH, OUTPUT_DIR,
    VAE_CKPT_PATH, DIFFUSION_CKPT_PATH, LATENT_STATS_PATH, HISTOGRAM_PATH,
    N_SAMPLES, MEL_TIME_DIVISOR,
    device,
)
